# Generated by Django 3.2.7 on 2021-09-21 05:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPostModel',
            new_name='PostModel',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='post_of_user',
            new_name='user',
        ),
    ]
