# Generated by Django 3.2.7 on 2021-09-21 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='massege',
            field=models.TextField(blank=True, null=True, verbose_name='massege'),
        ),
    ]
