# Generated by Django 3.2.7 on 2021-09-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postmodel_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='post_like',
            new_name='like',
        ),
    ]
