# Generated by Django 3.2.7 on 2021-09-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
