# Generated by Django 3.2.7 on 2021-09-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_postmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='username',
        ),
    ]
